---
title: " "
format:
  pdf:
    documentclass: article
    classoption: landscape
    papersize: "a4"
    fontsize: "11pt"
    mainfont: Arial
    # monofont: Fira Code
    geometry: 
      #- showframe
      - top=10mm
      - bottom=10mm
      - left=10mm
      - right=10mm
      - heightrounded
    # margin-left: "1cm"
    # margin-right: "1cm"
    # margin-top: "1cm"
    # margin-bottom: "1cm"
    include-in-header: 
      text: 
        \usepackage{makecell}
    
editor: source
keep-tex: true
---

```{r, include=FALSE}
## Calculated variables
library(dplyr)
library(kableExtra)

plot_code     <- "OOMSI01"
plot_location <- "OOMSIS"

dat <- tibble(
  quadrat = 2,
  tree_no = 1:10,
  tree_species = LETTERS[1:10],
  sf = c("?", rep("", 7), "?", ""),
  coord_east = sample(100:200, 10, replace = F), 
  coord_north = sample(200:300, 10, replace = F),
  tree_dbh_pom = 1.3,
  tree_dbh_previous = sample(15:100, 10, replace = T)
) 

col_empty <- c(
   "tree_dbh_current", "DBH_DF", "tree_status", "stem_form", "crown_position", "crown_form", "crown_d1",
   "crown_d2"   
   )

col_names <- c(
  "Quadrat", "Tree\nNo.", "Species\nCode", "SF", "East\n(m)", "North\n(m)", "POM\n(m)",
  "Previous\n(cm)", "Current\n(cm)", "DF", "Tree\nStatus", "Stem\nForm", "Position", "Form", "- d1 -", "- d2 -"
)

full_table <- dat

full_table[, col_empty] <- ""

full_table2 <- full_table |> mutate(across(everything(), as.character))

## add column number as first row
full_table3 <- setNames(paste0("(", 1:16, ")"), names(full_table2)) |> 
  bind_rows(full_table2)

```

<!-- TITLE COLUMN -->

:::: {layout="[0.2, 0.6, 0.2]"}
::: {.column width="20%"}
Form No.: **PSP/06**
:::

::: {.column width="60%"}
::: {.center data-latex=""}
**PLOT REASSESSMENT AND TREE DESCRIPTION**
:::
:::

::: {.column width="20%"}
::: {.flushright data-latex=""}
Page ___ of ___
:::
:::
::::

<!-- First line -->
:::: {layout="[0.2, 0.2, 0.2, 0.2, 0.2]"}
::: {.column width="20%"}
Plot number: **`{r} plot_code`**
:::

::: {.column width="20%"}
Location: **`{r} plot_location`**
:::

::: {.column width="20%"}
\  
:::

::: {.column width="20%"}
Assessed by: ...............
:::

::: {.column width="20%"}
::: {.flushright data-latex=""}
Date: ... / ... / ...
:::
:::
::::

<!-- TABLE -->

```{r, echo=F}

## GT package not good enough with PDF output, consider switching when better support
# library(gt)
# gt_colnames <- setNames(col_names, names(full_table))
# 
# gt_field_form <- full_table |> 
#   gt::gt() |>
#   gt::cols_label(!!!gt_colnames, .fn = md) |>
#   gt::tab_spanner(
#     label = "Coordinates",
#     columns = c(coord_east, coord_north)
#   ) |>
#   gt::tab_spanner(
#     label = "DBH/DAB",
#     columns = c(tree_dbh_pom, tree_dbh_previous, tree_dbh_current)
#   ) |>
#   gt::tab_spanner(
#     label = "Diameter (m)",
#     columns = c(crown_d1, crown_d2)
#   ) |>
#   gt::tab_spanner(
#     label = "Crown",
#     columns = starts_with("crown_")
#   ) |>
#   tab_style(
#     style = cell_borders(
#       sides = "all",
#       color = "#000000",
#       style = "solid",
#       #weight = px(2)
#       ),
#     locations = cells_body()
#   )

# gt_field_form

```

```{r, echo=FALSE}

## Style 1srt row same as headers
vec_row1 <- c(T, rep(F, nrow(full_table3) - 1)) 

kbl_field_form <- full_table3 |> 
  kbl(
    col.names = linebreak(col_names),
    escape = F,
    booktabs = F,
    align = "c"
  ) |> 
  kable_styling(
    font_size = 7, 
    #bootstrap_options = "condensed",
    latex_options = c("scale_up", "HOLD_position")
  ) |>
  add_header_above(
    c(" " = 1, " " = 1," " = 1," " = 1,"Coordinates" = 2, "DBH/DAB" = 4, " " = 1, " " = 1, " " = 1, " " = 1, "Diameter (cm)" = 2),
    border_left = T, border_right = T, bold = T
  ) |>
  add_header_above(
    c(" " = 1, " " = 1," " = 1," " = 1, " " = 2, " " = 4,  " " = 1, " " = 1, "Crown" = 4), 
    border_left = T, border_right = T, bold = T
  ) |>
  row_spec(0, bold = T) |>
  column_spec(1, border_left = T, bold = vec_row1, monospace = !vec_row1) |>
  column_spec(2:8, bold = vec_row1, monospace = !vec_row1) |>
  column_spec(16, border_right = T) |>
  row_spec(1, bold = T)

kbl_field_form

```
